### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by rolandtritsch** [coacoas/gradle-ensime#4]
Hi all, I am porting the Android UI samples to Scala and want to use the plugin to generate an .ensime file.

The error message I am getting is >Unsupported major.minor version 52.0<.

The output and the .../Application/build.gradle file is below.

Regards ...
    Roland

---

master *=:ActionBarCompat-Basic> ./gradlew ensime

FAILURE: Build failed with an exception.

* Where:
Build file '/Development/Work/scala-android-ui-samples/ActionBarCompat-Basic/Application/build.gradle' line: 15

* What went wrong:
A problem occurred evaluating project ':Application'.
> net/coacoas/gradle/plugins/Ensime : Unsupported major.minor version 52.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.87 secs
master *=:ActionBarCompat-Basic> ./gradlew -v

------------------------------------------------------------
Gradle 2.2.1
------------------------------------------------------------

Build time:   2014-11-24 09:45:35 UTC
Build number: none
Revision:     6fcb59c06f43a4e6b1bcb401f7686a8601a1fb4a

Groovy:       2.3.6
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.7.0_55 (Oracle Corporation 24.55-b03)
OS:           Mac OS X 10.10.1 x86_64

---

buildscript {
    repositories {
        jcenter()
	mavenCentral()
    }

    dependencies {
        classpath "com.android.tools.build:gradle:1.0.0"
        classpath "com.novoda:gradle-android-command-plugin:1.3.0"
        classpath "jp.leafytree.gradle:gradle-android-scala-plugin:1.3.1"
        classpath "net.coacoas.gradle:gradle-ensime:0.1.10"
	}
}

apply plugin: "ensime"
apply plugin: "android-command"
apply plugin: "com.android.application"
apply plugin: "jp.leafytree.android-scala"

repositories {
    jcenter()
}

dependencies {
    compile "com.android.support:support-v4:21.0.2"
    compile "com.android.support:gridlayout-v7:21.0.2"
    compile "com.android.support:cardview-v7:21.0.2"
    compile "com.android.support:appcompat-v7:21.0.2"

    compile "org.scala-lang:scala-library:2.11.4"
}

// The sample build uses multiple directories to
// keep boilerplate and common code separate from
// the main sample code.
List<String> dirs = [
    "main",     // main sample code; look here for the interesting stuff.
    "common",   // components that are reused by multiple samples
    "template"  // boilerplate code that is generated by the sample template process
]

android {
    compileSdkVersion 21
    buildToolsVersion "21.1.1"

    defaultConfig {
        minSdkVersion 7
        targetSdkVersion 21
    }

    sourceSets {
        main {
            dirs.each { dir ->
                scala.srcDirs "src/${dir}/scala"
                res.srcDirs "src/${dir}/res"
            }
        }
        androidTest.setRoot("tests")
        androidTest.java.srcDirs = ["tests/src"]
    }

    lintOptions {
        abortOnError false
    }
}

**Comment by DavidOhsie** [comment]
The version of the .jar file in the maven central is compiled for java 8 and you are using java 7.  You may need to upgrade to java 8 or else I suppose you could recompile the project yourself for java 7.

**Comment by rolandtritsch** [comment]
Thanks. Done. This issue can be closed. - RT

On 9 January 2015 at 06:28, DavidOhsie <notifications@github.com> wrote:

> The version of the .jar file in the maven central is compiled for java 8
> and you are using java 7. You may need to upgrade to java 8 or else I
> suppose you could recompile the project yourself for java 7.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/coacoas/gradle-ensime/issues/4#issuecomment-69298506>.
>



-- 
e: roland@tritsch.org
m: +353-86-8563975
s: rolandtritsch
---
http://trits.ch/rt-qr-code
http://trits.ch/rt-linked-in
http://www.tritsch.org

**Comment by coacoas** [comment]
This was fixed in 0.1.11.  Java 6 is all that is required at this point.
